apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: calbwr8wc-nodejs
  janus-idp.io/tekton: calbwr8wc-nodejs
  backstage.io/kubernetes-id: calbwr8wc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: calbwr8wc-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
